name: deploy-pr

on:
  pull_request:
    paths:
      - "app/**"
      - ".github/workflows/deploy-pr.yml"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
        # Usage Github Actions Marketplace: https://github.com/marketplace?type=actions
      - name: Checkout repository
        # Usage: https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }} # マニフェストレポジトリがある場合は、アクセストークンを指定する

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}


      - name: Login to Github container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build And Push Github registry
        uses: docker/build-push-action@v5
        with:
          context: app
          push: true
          tags: ${{ steps.meta.outputs.tags }} # ghcr.io/darmadevZone/fastapi-sample:pr-xxx
          label: ${{ steps.meta.outputs.labels }}
